# Generated by Django 2.2.1 on 2019-10-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phoneNumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
