# Generated by Django 2.2.1 on 2019-10-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phoneNumber',
            field=models.CharField(max_length=11),
        ),
    ]
